# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Sample.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Sample.proto',
  package='',
  serialized_pb='\n\x0cSample.proto\"\x8e\x02\n\x06Sample\x12\x12\n\nSystemTime\x18\x01 \x02(\r\x12\x17\n\x0f\x43omputationTime\x18\x02 \x02(\r\x12\x13\n\x0bSystemState\x18\x03 \x02(\r\x12\x19\n\x07\x65ncoder\x18\x04 \x02(\x0b\x32\x08.Encoder\x12\x1b\n\x08setpoint\x18\x05 \x02(\x0b\x32\t.SetPoint\x12#\n\x0cmotorcurrent\x18\x06 \x02(\x0b\x32\r.MotorCurrent\x12#\n\x07mpu6050\x18\x07 \x01(\x0b\x32\x12.InvensenseMPU6050\x12\x1c\n\x08\x65stimate\x18\x08 \x01(\x0b\x32\n.Estimator\x12\"\n\x0byaw_rate_pi\x18\t \x01(\x0b\x32\r.PIController\"\xac\x01\n\x11InvensenseMPU6050\x12\x16\n\x0e\x41\x63\x63\x65lerometerX\x18\x01 \x02(\x02\x12\x16\n\x0e\x41\x63\x63\x65lerometerY\x18\x02 \x02(\x02\x12\x16\n\x0e\x41\x63\x63\x65lerometerZ\x18\x03 \x02(\x02\x12\x13\n\x0bTemperature\x18\x04 \x02(\x02\x12\x12\n\nGyroscopeX\x18\x05 \x02(\x02\x12\x12\n\nGyroscopeY\x18\x06 \x02(\x02\x12\x12\n\nGyroscopeZ\x18\x07 \x02(\x02\"W\n\x07\x45ncoder\x12\x16\n\x0eRearWheelCount\x18\x01 \x02(\r\x12\x11\n\tRearWheel\x18\x02 \x02(\x02\x12\r\n\x05Steer\x18\x03 \x02(\x02\x12\x12\n\nFrontWheel\x18\x04 \x02(\x02\"0\n\x0cMotorCurrent\x12\x11\n\tRearWheel\x18\x01 \x02(\x02\x12\r\n\x05Steer\x18\x02 \x02(\x02\"0\n\x08SetPoint\x12\x13\n\x0btheta_R_dot\x18\x01 \x02(\x02\x12\x0f\n\x07psi_dot\x18\x02 \x02(\x02\"\x81\x01\n\tEstimator\x12\x0b\n\x03phi\x18\x01 \x02(\x02\x12\r\n\x05\x64\x65lta\x18\x02 \x02(\x02\x12\x0f\n\x07phi_dot\x18\x03 \x02(\x02\x12\x11\n\tdelta_dot\x18\x04 \x02(\x02\x12\x19\n\x11theta_R_dot_lower\x18\x05 \x02(\x02\x12\x19\n\x11theta_R_dot_upper\x18\x06 \x02(\x02\"<\n\x0cPIController\x12\t\n\x01\x65\x18\x01 \x02(\x02\x12\n\n\x02Kp\x18\x02 \x02(\x02\x12\n\n\x02Ki\x18\x03 \x02(\x02\x12\t\n\x01x\x18\x04 \x02(\x02')




_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SystemTime', full_name='Sample.SystemTime', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ComputationTime', full_name='Sample.ComputationTime', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SystemState', full_name='Sample.SystemState', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encoder', full_name='Sample.encoder', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='setpoint', full_name='Sample.setpoint', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motorcurrent', full_name='Sample.motorcurrent', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mpu6050', full_name='Sample.mpu6050', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='estimate', full_name='Sample.estimate', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw_rate_pi', full_name='Sample.yaw_rate_pi', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=17,
  serialized_end=287,
)


_INVENSENSEMPU6050 = _descriptor.Descriptor(
  name='InvensenseMPU6050',
  full_name='InvensenseMPU6050',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AccelerometerX', full_name='InvensenseMPU6050.AccelerometerX', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AccelerometerY', full_name='InvensenseMPU6050.AccelerometerY', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AccelerometerZ', full_name='InvensenseMPU6050.AccelerometerZ', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Temperature', full_name='InvensenseMPU6050.Temperature', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GyroscopeX', full_name='InvensenseMPU6050.GyroscopeX', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GyroscopeY', full_name='InvensenseMPU6050.GyroscopeY', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GyroscopeZ', full_name='InvensenseMPU6050.GyroscopeZ', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=290,
  serialized_end=462,
)


_ENCODER = _descriptor.Descriptor(
  name='Encoder',
  full_name='Encoder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RearWheelCount', full_name='Encoder.RearWheelCount', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RearWheel', full_name='Encoder.RearWheel', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Steer', full_name='Encoder.Steer', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FrontWheel', full_name='Encoder.FrontWheel', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=464,
  serialized_end=551,
)


_MOTORCURRENT = _descriptor.Descriptor(
  name='MotorCurrent',
  full_name='MotorCurrent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RearWheel', full_name='MotorCurrent.RearWheel', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Steer', full_name='MotorCurrent.Steer', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=553,
  serialized_end=601,
)


_SETPOINT = _descriptor.Descriptor(
  name='SetPoint',
  full_name='SetPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='theta_R_dot', full_name='SetPoint.theta_R_dot', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='psi_dot', full_name='SetPoint.psi_dot', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=603,
  serialized_end=651,
)


_ESTIMATOR = _descriptor.Descriptor(
  name='Estimator',
  full_name='Estimator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phi', full_name='Estimator.phi', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delta', full_name='Estimator.delta', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phi_dot', full_name='Estimator.phi_dot', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delta_dot', full_name='Estimator.delta_dot', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='theta_R_dot_lower', full_name='Estimator.theta_R_dot_lower', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='theta_R_dot_upper', full_name='Estimator.theta_R_dot_upper', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=654,
  serialized_end=783,
)


_PICONTROLLER = _descriptor.Descriptor(
  name='PIController',
  full_name='PIController',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='e', full_name='PIController.e', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Kp', full_name='PIController.Kp', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Ki', full_name='PIController.Ki', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='PIController.x', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=785,
  serialized_end=845,
)

_SAMPLE.fields_by_name['encoder'].message_type = _ENCODER
_SAMPLE.fields_by_name['setpoint'].message_type = _SETPOINT
_SAMPLE.fields_by_name['motorcurrent'].message_type = _MOTORCURRENT
_SAMPLE.fields_by_name['mpu6050'].message_type = _INVENSENSEMPU6050
_SAMPLE.fields_by_name['estimate'].message_type = _ESTIMATOR
_SAMPLE.fields_by_name['yaw_rate_pi'].message_type = _PICONTROLLER
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
DESCRIPTOR.message_types_by_name['InvensenseMPU6050'] = _INVENSENSEMPU6050
DESCRIPTOR.message_types_by_name['Encoder'] = _ENCODER
DESCRIPTOR.message_types_by_name['MotorCurrent'] = _MOTORCURRENT
DESCRIPTOR.message_types_by_name['SetPoint'] = _SETPOINT
DESCRIPTOR.message_types_by_name['Estimator'] = _ESTIMATOR
DESCRIPTOR.message_types_by_name['PIController'] = _PICONTROLLER

class Sample(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SAMPLE

  # @@protoc_insertion_point(class_scope:Sample)

class InvensenseMPU6050(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INVENSENSEMPU6050

  # @@protoc_insertion_point(class_scope:InvensenseMPU6050)

class Encoder(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENCODER

  # @@protoc_insertion_point(class_scope:Encoder)

class MotorCurrent(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MOTORCURRENT

  # @@protoc_insertion_point(class_scope:MotorCurrent)

class SetPoint(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SETPOINT

  # @@protoc_insertion_point(class_scope:SetPoint)

class Estimator(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ESTIMATOR

  # @@protoc_insertion_point(class_scope:Estimator)

class PIController(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PICONTROLLER

  # @@protoc_insertion_point(class_scope:PIController)


# @@protoc_insertion_point(module_scope)
