# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='',
  serialized_pb='\n\x0csample.proto\"\x93\x02\n\x06Sample\x12\x13\n\x0bsystem_time\x18\x01 \x02(\r\x12\x18\n\x10\x63omputation_time\x18\x02 \x02(\r\x12\x14\n\x0csystem_state\x18\x03 \x02(\r\x12\x19\n\x07\x65ncoder\x18\x04 \x02(\x0b\x32\x08.Encoder\x12\x1c\n\tset_point\x18\x05 \x02(\x0b\x32\t.SetPoint\x12$\n\rmotor_current\x18\x06 \x02(\x0b\x32\r.MotorCurrent\x12#\n\x07mpu6050\x18\x07 \x01(\x0b\x32\x12.InvensenseMPU6050\x12\x1c\n\x08\x65stimate\x18\x08 \x01(\x0b\x32\n.Estimator\x12\"\n\x0byaw_rate_pi\x18\t \x01(\x0b\x32\r.PIController\"\xb2\x01\n\x11InvensenseMPU6050\x12\x17\n\x0f\x61\x63\x63\x65lerometer_x\x18\x01 \x02(\x02\x12\x17\n\x0f\x61\x63\x63\x65lerometer_y\x18\x02 \x02(\x02\x12\x17\n\x0f\x61\x63\x63\x65lerometer_z\x18\x03 \x02(\x02\x12\x13\n\x0btemperature\x18\x04 \x02(\x02\x12\x13\n\x0bgyroscope_x\x18\x05 \x02(\x02\x12\x13\n\x0bgyroscope_y\x18\x06 \x02(\x02\x12\x13\n\x0bgyroscope_z\x18\x07 \x02(\x02\"[\n\x07\x45ncoder\x12\x18\n\x10rear_wheel_count\x18\x01 \x02(\r\x12\x12\n\nrear_wheel\x18\x02 \x02(\x02\x12\r\n\x05steer\x18\x03 \x02(\x02\x12\x13\n\x0b\x66ront_wheel\x18\x04 \x02(\x02\"1\n\x0cMotorCurrent\x12\x12\n\nrear_wheel\x18\x01 \x02(\x02\x12\r\n\x05steer\x18\x02 \x02(\x02\"0\n\x08SetPoint\x12\x13\n\x0btheta_R_dot\x18\x01 \x02(\x02\x12\x0f\n\x07psi_dot\x18\x02 \x02(\x02\"\x81\x01\n\tEstimator\x12\x0b\n\x03phi\x18\x01 \x02(\x02\x12\r\n\x05\x64\x65lta\x18\x02 \x02(\x02\x12\x0f\n\x07phi_dot\x18\x03 \x02(\x02\x12\x11\n\tdelta_dot\x18\x04 \x02(\x02\x12\x19\n\x11theta_R_dot_lower\x18\x05 \x02(\x02\x12\x19\n\x11theta_R_dot_upper\x18\x06 \x02(\x02\"<\n\x0cPIController\x12\t\n\x01\x65\x18\x01 \x02(\x02\x12\n\n\x02Kp\x18\x02 \x02(\x02\x12\n\n\x02Ki\x18\x03 \x02(\x02\x12\t\n\x01x\x18\x04 \x02(\x02')




_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='system_time', full_name='Sample.system_time', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='computation_time', full_name='Sample.computation_time', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_state', full_name='Sample.system_state', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encoder', full_name='Sample.encoder', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='set_point', full_name='Sample.set_point', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motor_current', full_name='Sample.motor_current', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mpu6050', full_name='Sample.mpu6050', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='estimate', full_name='Sample.estimate', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw_rate_pi', full_name='Sample.yaw_rate_pi', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=17,
  serialized_end=292,
)


_INVENSENSEMPU6050 = _descriptor.Descriptor(
  name='InvensenseMPU6050',
  full_name='InvensenseMPU6050',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accelerometer_x', full_name='InvensenseMPU6050.accelerometer_x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accelerometer_y', full_name='InvensenseMPU6050.accelerometer_y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accelerometer_z', full_name='InvensenseMPU6050.accelerometer_z', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='InvensenseMPU6050.temperature', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gyroscope_x', full_name='InvensenseMPU6050.gyroscope_x', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gyroscope_y', full_name='InvensenseMPU6050.gyroscope_y', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gyroscope_z', full_name='InvensenseMPU6050.gyroscope_z', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=295,
  serialized_end=473,
)


_ENCODER = _descriptor.Descriptor(
  name='Encoder',
  full_name='Encoder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rear_wheel_count', full_name='Encoder.rear_wheel_count', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rear_wheel', full_name='Encoder.rear_wheel', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='steer', full_name='Encoder.steer', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='front_wheel', full_name='Encoder.front_wheel', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=475,
  serialized_end=566,
)


_MOTORCURRENT = _descriptor.Descriptor(
  name='MotorCurrent',
  full_name='MotorCurrent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rear_wheel', full_name='MotorCurrent.rear_wheel', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='steer', full_name='MotorCurrent.steer', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=568,
  serialized_end=617,
)


_SETPOINT = _descriptor.Descriptor(
  name='SetPoint',
  full_name='SetPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='theta_R_dot', full_name='SetPoint.theta_R_dot', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='psi_dot', full_name='SetPoint.psi_dot', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=619,
  serialized_end=667,
)


_ESTIMATOR = _descriptor.Descriptor(
  name='Estimator',
  full_name='Estimator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phi', full_name='Estimator.phi', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delta', full_name='Estimator.delta', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phi_dot', full_name='Estimator.phi_dot', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delta_dot', full_name='Estimator.delta_dot', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='theta_R_dot_lower', full_name='Estimator.theta_R_dot_lower', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='theta_R_dot_upper', full_name='Estimator.theta_R_dot_upper', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=670,
  serialized_end=799,
)


_PICONTROLLER = _descriptor.Descriptor(
  name='PIController',
  full_name='PIController',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='e', full_name='PIController.e', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Kp', full_name='PIController.Kp', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Ki', full_name='PIController.Ki', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='PIController.x', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=801,
  serialized_end=861,
)

_SAMPLE.fields_by_name['encoder'].message_type = _ENCODER
_SAMPLE.fields_by_name['set_point'].message_type = _SETPOINT
_SAMPLE.fields_by_name['motor_current'].message_type = _MOTORCURRENT
_SAMPLE.fields_by_name['mpu6050'].message_type = _INVENSENSEMPU6050
_SAMPLE.fields_by_name['estimate'].message_type = _ESTIMATOR
_SAMPLE.fields_by_name['yaw_rate_pi'].message_type = _PICONTROLLER
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
DESCRIPTOR.message_types_by_name['InvensenseMPU6050'] = _INVENSENSEMPU6050
DESCRIPTOR.message_types_by_name['Encoder'] = _ENCODER
DESCRIPTOR.message_types_by_name['MotorCurrent'] = _MOTORCURRENT
DESCRIPTOR.message_types_by_name['SetPoint'] = _SETPOINT
DESCRIPTOR.message_types_by_name['Estimator'] = _ESTIMATOR
DESCRIPTOR.message_types_by_name['PIController'] = _PICONTROLLER

class Sample(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SAMPLE

  # @@protoc_insertion_point(class_scope:Sample)

class InvensenseMPU6050(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INVENSENSEMPU6050

  # @@protoc_insertion_point(class_scope:InvensenseMPU6050)

class Encoder(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENCODER

  # @@protoc_insertion_point(class_scope:Encoder)

class MotorCurrent(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MOTORCURRENT

  # @@protoc_insertion_point(class_scope:MotorCurrent)

class SetPoint(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SETPOINT

  # @@protoc_insertion_point(class_scope:SetPoint)

class Estimator(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ESTIMATOR

  # @@protoc_insertion_point(class_scope:Estimator)

class PIController(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PICONTROLLER

  # @@protoc_insertion_point(class_scope:PIController)


# @@protoc_insertion_point(module_scope)
