#!/bin/sh

ROOT_DIR=$(git rev-parse --show-toplevel)
cd $ROOT_DIR
SUBMODULES=$(grep path ${ROOT_DIR}/.gitmodules | sed 's/^.*path = //')
CHIBIOS_SUBMODULE=$(echo "$SUBMODULES" | grep ChibiOS)
for SUBMODULE in $SUBMODULES; do
	if ! [ "$(ls -A ${SUBMODULE})" ]; then
		git submodule init
		git submodule update
	fi
done

NUM_DIFF_SUBS_CLEAN=$(git diff --name-only --ignore-submodules=dirty | grep -F "$SUBMODULES" | wc -l)
NUM_DIFF_SUBS=$(git diff --name-only | grep -F "$SUBMODULES" | wc -l)
# skip update if any submodules are dirty
if [ "$NUM_DIFF_SUBS" -eq "$NUM_DIFF_SUBS_CLEAN" ]; then
	git submodule update
	RETVAL=$?
	if [ $RETVAL -ne 0 ]; then
	# if update fails, try adding additional remotes and updating again
		cd ${ROOT_DIR}/${CHIBIOS_SUBMODULE}
		git remote add tegesoft git://github.com/tegesoft/ChibiOS.git
		git fetch tegesoft
		git remote add oliverlee git://github.com/oliverlee/ChibiOS.git
		git fetch oliverlee
		cd $ROOT_DIR
		git submodule update
	fi
fi
