/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.2-dev at Fri Apr 19 15:13:42 2013. */

#include "Test.pb.h"



const pb_field_t Test_fields[19] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC, Test, SystemTime, SystemTime, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC, Test, ComputationTime, SystemTime, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC, Test, RearWheelAngle, ComputationTime, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC, Test, SteerAngle, RearWheelAngle, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC, Test, FrontWheelAngle, SteerAngle, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC, Test, RearWheelRate_sp, FrontWheelAngle, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC, Test, YawRate_sp, RearWheelRate_sp, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC, Test, RearWheelMotorCurrent, YawRate_sp, 0),
    PB_FIELD(  9, FLOAT   , REQUIRED, STATIC, Test, SteerMotorCurrent, RearWheelMotorCurrent, 0),
    PB_FIELD( 10, FLOAT   , REQUIRED, STATIC, Test, AccelerometerX, SteerMotorCurrent, 0),
    PB_FIELD( 11, FLOAT   , REQUIRED, STATIC, Test, AccelerometerY, AccelerometerX, 0),
    PB_FIELD( 12, FLOAT   , REQUIRED, STATIC, Test, AccelerometerZ, AccelerometerY, 0),
    PB_FIELD( 13, FLOAT   , REQUIRED, STATIC, Test, Temperature, AccelerometerZ, 0),
    PB_FIELD( 14, FLOAT   , REQUIRED, STATIC, Test, GyroscopeX, Temperature, 0),
    PB_FIELD( 15, FLOAT   , REQUIRED, STATIC, Test, GyroscopeY, GyroscopeX, 0),
    PB_FIELD( 16, FLOAT   , REQUIRED, STATIC, Test, GyroscopeZ, GyroscopeY, 0),
    PB_FIELD( 17, UINT32  , REQUIRED, STATIC, Test, SystemState, GyroscopeZ, 0),
    PB_FIELD( 18, MESSAGE , OPTIONAL, STATIC, Test, x_est, SystemState, &EstimatorState_fields),
    PB_LAST_FIELD
};

const pb_field_t EstimatorState_fields[5] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC, EstimatorState, phi, phi, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC, EstimatorState, delta, phi, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC, EstimatorState, phi_dot, delta, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC, EstimatorState, delta_dot, phi_dot, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
STATIC_ASSERT((pb_membersize(Test, x_est) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Test_EstimatorState)
#endif

#if !defined(PB_FIELD_32BIT)
STATIC_ASSERT((pb_membersize(Test, x_est) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Test_EstimatorState)
#endif

