/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.2-dev at Fri Apr 19 15:13:42 2013. */

#ifndef _PB_TEST_PB_H_
#define _PB_TEST_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _EstimatorState {
    float phi;
    float delta;
    float phi_dot;
    float delta_dot;
} EstimatorState;

typedef struct _Test {
    uint32_t SystemTime;
    float ComputationTime;
    float RearWheelAngle;
    float SteerAngle;
    float FrontWheelAngle;
    float RearWheelRate_sp;
    float YawRate_sp;
    float RearWheelMotorCurrent;
    float SteerMotorCurrent;
    float AccelerometerX;
    float AccelerometerY;
    float AccelerometerZ;
    float Temperature;
    float GyroscopeX;
    float GyroscopeY;
    float GyroscopeZ;
    uint32_t SystemState;
    bool has_x_est;
    EstimatorState x_est;
} Test;

/* Default values for struct fields */

/* Struct field encoding specification for nanopb */
extern const pb_field_t Test_fields[19];
extern const pb_field_t EstimatorState_fields[5];

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
